import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Travor",
    template: "%s | Next.js 14",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen regular-18 leading-[1.67] ${inter.className}`}
      >
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
